import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { ToggleTheme } from '@/components/toggle-theme';
import { CreateDropDowMenu } from './components/create-dropdow-menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster />
          <div className="border-b">
            <div className="flex h-16 items-center px-48">
              <ToggleTheme />
              {/* <MainNav className="mx-6" /> */}
              <div className="ml-auto flex items-center space-x-4">
                {/* <Search /> */}
                {/* <UserNav /> */}
                <CreateDropDowMenu />
              </div>
            </div>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
